spring.application.name=RestSecurityTaskManagementSystem

spring.datasource.url=${DB_URL}jdbc:postgresql://ep-blue-fog-awqdh183-pooler.c-12.us-east-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate


logging.level.root=INFO
logging.level.com.example=DEBUG
logging.file.name=logs/app.logs
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss}  [%thread] %-5level %logger{36} - %msg%n


spring.flyway.enabled=true

jwt.secret=${JWT_SECRET}
jwt.access-token-expiration-ms=${JWT_ACCESS_EXP}
jwt.refresh-token-expiration-ms=${JWT_REFRESH_EXP}


#spring.security.oauth2.client.registration.github.client-id=${CLIENT_ID}
#spring.security.oauth2.client.registration.github.client-secret=${CLIENT_SECRET}
#spring.security.oauth2.client.registration.github.scope=read:user,user:email
